### ISSUE TITLE
URP Support

### ISSUE THREAD

**Issue by mjcguada** [Swegrock/Dynamic-Splitscreen#3]
Hi! I've changed my render pipeline to URP and the splitscreen is not working. Any idea?

![image](https://user-images.githubusercontent.com/22896054/95769214-d3639780-0cb7-11eb-8b51-8cb54e5b7160.png)

**Comment by sebheron** [comment]
Hi Mario,
Can you link me your project and I'll see if I can help?
Thanks

**Comment by mjcguada** [comment]
Sure! https://github.com/mjcguada/DynamicSplitScreenURP

I've created a new version of Splitscreen shader but it doesn't work neither. I hope there's a solution.
I don't if it has something to do with Camera stacking or Idk

Thanks in advance!

**Comment by sebheron** [comment]
Right okay, so after a quick investigation into your project and a little reading on URP.
The issue seems to stem from the fact URP doesn't use traditional camera depth instead it uses Camera Stacking. I'm not too familiar with Camera Stacking (there's a document for it [here](https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@7.2/manual/camera-stacking.html)), I'd assume you'd need to set the main camera as an Overlay camera of the generated splitscreen camera which would be the Base camera.
This could easily be done in code with a few lines, let me know how you get along, I've got 2nd year uni work to deal with at the moment, but I'll try to offer help where I can 😃.

**Comment by mjcguada** [comment]
I've managed to get it done just and hour ago and that's exactly the way I accomplished it.

Right now I must release a demo of the game I'm working on, but I would love to help you with those lines of code.

I think I can send it to you by Friday or Saturday.

Thanks again for your help and your nice code

Kind regards,

Mario.

**Comment by sebheron** [comment]
Absolutely, the code is under the MIT licence so if you'd like I can put a link to your GitHub page for the URP version in the readme if you'd like. Would definitely like to see how you managed to get it to work.
Good luck with the rest of the project!
Thanks,
Seb
